"""Agregue tabla seccion

Revision ID: 41515c4a6be5
Revises: 6ed7f0b0784e
Create Date: 2023-03-03 20:59:48.883711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41515c4a6be5'
down_revision = '6ed7f0b0784e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('alumnos', sa.Integer(), nullable=True),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('maestro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maestro_id'], ['maestros.id'], ),
    sa.ForeignKeyConstraint(['nivel_id'], ['niveles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secciones')
    # ### end Alembic commands ###
